######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 22 10:37:32 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .../include
INCLUDEPATH += ../include

# Input
QT += opengl
HEADERS = SampleDemo.h \
  ../include/Rigid2D.h

SOURCES = examples.cpp \
  SampleDemo.cpp \
  ../include/Objects/*.cpp \
  ../include/Common/*.cpp

CXXFLAGS += -std=c++0x
